### ISSUE TITLE
Grind early game

### ISSUE THREAD

**Issue by Enryco** [DevDyna/IronBerry#10]
### Core Section

- [X] I have searched for this issue on this repository
- [X] I like what you are doing

### Case Section

- [ ] New Mod to add and why
- [ ] Enable a disabled item with X scope

### Description

The ealy game grind is on fire. I encountered many obstacles in terms of time and jumping. For making a lot of things you need iron. Not much, but a decent amount. The rate in awfull, and every single item you need to obtain jumping. At the start it's pretty fun, but after a while it's getting annoing. I tried to "automate" the process, but even after that i just want to go afk while jumping to obtain resource. The problem with iron is coal. You obtain 8 coal from a stack of dirt, and you get 4 iron because it's divided by 2.
![2024-01-24_10 54 54](https://github.com/DevDyna/IronBerry/assets/80041511/e8a4ab7b-56ea-42d5-a0fd-594cce138513)
I can block the space button and leave the pc for an hour in this setup to obtain coal, but i mean it's early game, and i already need to afk?
The fact that you obtain copper with iron (and glowstone), and that the copper is require in block doens't help.
Now i'm tring to rush to a vanilla furnace to obtain a normal amount of iron, it seems the only way

Since it was in the quest, I make the egg analyzer. 13 iron ingot :/
But why i waste all of that iron? For analizing egg you also need redstone. And the analazing can fail. So you use iron, and restone, for an agg that has a percentage of spawning a bird? The quest stop to the analizer, so why would you invest so much resource in this

I'm i missing something obvius, or is this intend?

### Missing Your Case ?

early game

### Additional things

Mybe a shop with iron coin where you can buy like a stack of iron or coal?

**Comment by DevDyna** [comment]
> and i already need to afk?

on early game grind iron is essential for anything , 
it have a bad efficiency with alloy furnace but after unlock chap 2 (tombstone)  it can be increase

> Since it was in the quest, I make the egg analyzer. 13 iron ingot :/

ik , it is strange machine to make early game only to analyze eggs but it can be essential on future progress

> Mybe a shop with iron coin where you can buy like a stack of iron or coal?

not a bad idea , it was on original idea of this modpack but removed due too strange but i can rollback

**Comment by DevDyna** [comment]
released a 0.7d with a shop system where everyone can obtain and buy using coins some stuff included iron

**Comment by Enryco** [comment]
> released a 0.7d with a shop system where everyone can obtain and buy using coins some stuff included iron

I see the patch notes, but how early is the shop? I can't find a recipe for the amadron tablet, and even if i'll obtain it it will be already full of pressure? Or there is a new quest that gives it to you?
I love the recipe for the coin, it will be so helpful for the start!

**Comment by DevDyna** [comment]
>  I can't find a recipe for the amadron tablet

it was intended due can be only obtained as quest reward

##
>  if i'll obtain it it will be already full of pressure? 

also with max volume upgrades to be used more times before need to be recharged

##
> Or there is a new quest that gives it to you?

true , on age 1 (after unlock iron ingot)

**Comment by DevDyna** [comment]
> > I can't find a recipe for the amadron tablet
> 
> it was intended due can be only obtained as quest reward and  dont want on any way used too much
> 
> > if i'll obtain it it will be already full of pressure?
> 
> also with max volume upgrades to be used more times before need to be recharged
> 
> > Or there is a new quest that gives it to you?
> 
> true , on age 1 (after unlock iron ingot)
