### ISSUE TITLE
bug - Mechanical Squeezer and Roots Classic

### ISSUE THREAD

**Issue by Tivrusky4th** [DevDyna/IronBerry#11]
### Core Section

- [X] I have searched for this issue on this repository
- [X] This bug persist and I need help

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.8b

### Description

The Mechanical Squeezer is unable to proccess the berries from Roots Classic.

### Procedure

Putting one of the berries into the mechanical squeezer uses some power but does not do the crafting procces.

### Additional things

N/A

**Comment by DevDyna** [comment]
thank for reporting this bug!

**Comment by Tivrusky4th** [comment]
your welcome.
great modpack so far!

**Comment by DevDyna** [comment]
fixed on release 0.8c
