### ISSUE TITLE
Ice

### ISSUE THREAD

**Issue by BigAlzBub** [DevDyna/IronBerry#13]
### Core Section

- [X] I have searched for this issue on this repository
- [X] This bug persist and I need help

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

Ironberry Expert 0.8b

### Description

I can't seem to find a way to make ice.  I would imagine that the Entropy Manipulator ought to be able to make ice but it doesn't seem to do it.

### Procedure

I have charged up the Entropy Manipulator, and from what I can tell from various Youtube videos, when you shift right click a water source, it ought freeze the water, at which point you can break the ice into shards, then combine the shards to make ice.  However this does not seem to be working.  Is there an alternate way of making Ice that I'm missing?

### Additional things

N/A

**Comment by BigAlzBub** [comment]
Unfortunately I can't find a way to make normal ice, other than platforming out like crazy and hoping to find a chilly biome where water naturally freezes.

**Comment by DevDyna** [comment]
> Unfortunately I can't find a way to make normal ice, other than platforming out like crazy and hoping to find a chilly biome where water naturally freezes.

mh.. strange , maybe was disabled by other parts of temp-scripts that i didn't know , i will investigate

**Comment by DevDyna** [comment]
uploaded a 0.8d where all recipes are comeback but age 5 still not completed
