### ISSUE TITLE
Recipe conflict in crucible vs paper -> book and paper -> litmus paper

### ISSUE THREAD

**Issue by VorpalLemur** [DevDyna/IronBerry#16]
### Core Section

- [X] I have searched for this issue on this repository
- [X] This bug persist and I need help

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.8e

### Description

Litmus paper from the Reactive mod may be impossible to get due to recipe conflict.  According to JEI, paper + mind is supposed to get you litmus paper but it gets you book instead. 

### Procedure

follow JEI recipe to get litmus paper, get book instead

### Additional things

n/a

**Comment by DevDyna** [comment]
thank to report it! i will fix as soon as possible

**Comment by DevDyna** [comment]
uploaded 0.9a that fix it
