### ISSUE TITLE
Sourcestone

### ISSUE THREAD

**Issue by ZariusCorten** [DevDyna/IronBerry#17]
### Core Section

- [X] I have searched for this issue on this repository
- [X] This bug persist and I need help

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.9a

### Description

Sourcestone has no valid recipe. Per our conversation on Reddit, I am putting this in to remind you.. Thanks.

### Procedure

Attempted to find recipe in JNI. None exists.
Attempted to use default recipe. Non-functional.

### Additional things

No further data.

**Comment by DevDyna** [comment]
fixed on [`595ed30.a`](https://github.com/DevDyna/IronBerry/commit/595ed30b25c745dbba6826a074d83f800841cfb3#diff-e4726fa3d11a81e0cd55ff38ab0138d1b78cc4d5bb371bcf568fc6a65415b6f3) and [`595ed30.b`](https://github.com/DevDyna/IronBerry/commit/595ed30b25c745dbba6826a074d83f800841cfb3#diff-e462a913c8bd98b91a97df127ebf492a25eae1712574f6209adcf95dbb56b009)

**Comment by DevDyna** [comment]
[sended on Curseforge pending](https://legacy.curseforge.com/minecraft/modpacks/ironberry-expert/files/5387333)
