### ISSUE TITLE
Lectern recipe

### ISSUE THREAD

**Issue by ZariusCorten** [DevDyna/IronBerry#18]
### Core Section

- [X] I have searched for this issue on this repository
- [X] This bug persist and I need help

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.9b

### Description

Lectern recipe doesn't appear to exist.

### Procedure

N/A

### Additional things

N/A

**Comment by DevDyna** [comment]
Thanks to report all this issues!
I will investigate

**Comment by DevDyna** [comment]
released 0.9c with all bug fix
https://legacy.curseforge.com/minecraft/modpacks/ironberry-expert/files/5493431
