### ISSUE TITLE
Tank replication

### ISSUE THREAD

**Issue by ZariusCorten** [DevDyna/IronBerry#19]
### Core Section

- [X] I have searched for this issue on this repository
- [X] This bug persist and I need help

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.9b

### Description

Cyclic tanks, when used to fill Reactive crucibles, duplicate above the crucible randomly.

Further testing shows that Pneumaticraft tanks appear to do this as well. Presuming all forms of tanks do this.

### Procedure

Fill a tank with water and attempt to use it to fill Reactive Crucibles. It doesn't duplicate every time, but it does it pretty often.

### Additional things

Standing on top of the crucible when filling appears to prevent the erroneous spawn.

**Comment by DevDyna** [comment]
I think that was a mod issue but i can try to fix that

**Comment by ZariusCorten** [comment]
Ah, well, if it's a mod pack interaction issue, all you can really do is poke the relevant devs and hope they care enough to do something. I have *not* had that issue with buckets.

**Comment by DevDyna** [comment]
> if it's a mod pack interaction issue

Francly i didn't know that reactive crucible could support fluid tanks as input so...this is fine

> all you can really do is poke the relevant devs and hope they care enough to do something

yeah except that ironberry still on 1.19 so probably it wasn't anymore supported so it will be a good idea to fix overriding the problem 
(like some other big issues `NC:N <-> kubejs` or `exoticbirds <- tiab`)

**Comment by hjake123** [comment]
I've fixed the issue upstream. Tanks should work to fill the crucible correctly now.
