### ISSUE TITLE
Nuclearcraft Recipe issue

### ISSUE THREAD

**Issue by ZariusCorten** [DevDyna/IronBerry#20]
### Core Section

- [X] I have searched for this issue on this repository
- [X] This bug persist and I need help

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.9a

### Description

The Assembler and the Alloy Smelter use materials oddly when  ingredients aren't laid out. If the machine detects that the correct items are present for a known recipe, it will remove a number of items from slots based on the position the recipe says that they should be in. This can result in too many of some items and/or too few of other items to be used. Can also be used to produce effectively infinite of several items that only have three ingredients, in the case of the assembler.

### Procedure

Use the items for a recipe, but in the wrong slots.

### Additional things

![image](https://github.com/DevDyna/IronBerry/assets/76277844/b037b5a1-742d-4022-9d0a-0baab35583a4)

**Comment by DevDyna** [comment]
> Can also be used to produce effectively infinite of several items that only have three ingredients, in the case of the assembler

I have no words to describe that...
Maybe I have a possible *brute force* to fix that include to remove 79/81 recipes on assembler

**Comment by ZariusCorten** [comment]
Okay, well, looking at the recipe list, apparently the only one that isn't 1:1 is Bronze (Tin+3 copper).

![image](https://github.com/DevDyna/IronBerry/assets/76277844/029345c5-c7c6-4bfb-86a3-3d07f9045ad7)

![image](https://github.com/DevDyna/IronBerry/assets/76277844/e3a7f87d-5b72-4f9e-9cd9-78e8a7d96858)

Which sucks because Tin is mildly more annoying to get a hold of than I like. :P

**Comment by DevDyna** [comment]
> Okay, well, looking at the recipe list, apparently the only one that isn't 1:1 is Bronze (Tin+3 copper). [...]

ok I have found what cause the issue : it apparently was caused by tileentity that pickup a wrong item count so.. luckly i can try to fix on a easy way without need to convert every recipe like what happen with assembly

**Comment by DevDyna** [comment]
> Which sucks because Tin is mildly more annoying to get a hold of than I like. :P

also I have decided to increase a bit the item count of some alloys to be a bit "more easy" make it without use too many resources
[due it cost a bit more as "classic way" ]
