### ISSUE TITLE
Crafting table?

### ISSUE THREAD

**Issue by aswan1239** [DevDyna/IronBerry#23]
### Core Section

- [X] I have searched for this issue on this repository

### Stage Selection

Introduction

### MOD Selection

None

### QUEST Selection

None

### RECIPES / EVENTS Selection

Add / Include

### Summary

So I might just be stupid, but after cutting down the ironwood tree, I can't use 4 planks to make a crafting table.

**Comment by DevDyna** [comment]
Thanks for the question.... apparently some filter removed for the 10° times the crafting table recipe..
I will fix on a next hotfix

**Comment by DevDyna** [comment]
fixed https://legacy.curseforge.com/minecraft/modpacks/ironberry-expert/files/5493628
