### ISSUE TITLE
Crook issue?

### ISSUE THREAD

**Issue by ZariusCorten** [DevDyna/IronBerry#24]
### Core Section

- [X] I have searched for this issue on this repository
- [X] This bug persist and I need help
- [X] I'm using the latest version of this project
- [X] I'm try to reinstall it on a clean instance (common issue)

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.9b

### Description

Crooks don't drop berries from Leaf blocks. Not sure if that's as intended or not.

### Procedure

N/A

### Additional things

N/A

**Comment by DevDyna** [comment]
> Crooks don't drop berries from Leaf blocks. Not sure if that's as intended or not.

Common issue If combined on crafting grid two crooks , the result will lost the enchant
Also they dont increase too much the drop rate so could be normal that isn't like ex nihilo crooks

**Comment by DevDyna** [comment]
closed due lack of information and/or work as intended / not planned
