### ISSUE TITLE
Many recipes are broken due unknown source (0.9b -> 0.9chotfix2)

### ISSUE THREAD

**Issue by ZariusCorten** [DevDyna/IronBerry#31]
### Core Section

- [X] I have searched on opened [issues](https://github.com/DevDyna/IronBerry/issues) and [discussions](https://github.com/DevDyna/IronBerry/discussions) of this repository
- [X] I'm using the latest version of this project

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.9c hotfix 2

### Description

The Bed and Cutting Board recipes are non-functional. 

### Procedure

N/A

### Additional things

I feel like I'm nit-picking, though some of this stuff is pretty critical, especially with some of the added mods in the newest version.

**Comment by ZariusCorten** [comment]
Addendum: Stick recipe is also AWOL

**Comment by ZariusCorten** [comment]
Bark Knife recipe appears to be missing.

**Comment by DevDyna** [comment]
i will fix on later after i found what cause all of this missing recipes

**Comment by ZariusCorten** [comment]
No problem, I like what I'm seeing, so I want to help. As a note, Old Industrial Wood Planks are uncraftable, as well.

**Comment by DevDyna** [comment]
i have decided to unify this issue on [discussion](https://github.com/DevDyna/IronBerry/discussions/27) to allow to have a list of all recipes that need to be fixed 
(also i keep an eye on the main problem due it maybe cause many recipes as missing)
if you find more missing recipes you can write a comment below it and i will add
