### ISSUE TITLE
Improving automation ability a little?

### ISSUE THREAD

**Issue by ZariusCorten** [DevDyna/IronBerry#33]
### Core Section

- [X] I have searched for this issue on this repository

### Stage Selection

Campain 4

### MOD Selection

None

### QUEST Selection

None

### RECIPES / EVENTS Selection

Add / Include

### Other Selection

- [ ] Enable a disabled item with X scope

### Description

I'm wondering if we can add some of the recipes unique to the Blue Power Alloy Furnace to other machines? A prime example is the Generalized Twilight Prediction recipe. It's primary material and it's output are for machines at the end of Age 4, but the machine it uses from Age 1 is difficult to automate in general due to the fact that the machines don't have set slots, and have more slots than necessary. The first reason for this would be that adding the recipe to the NuclearCraft Alloy Smelter would significantly improve that automation capacity. The second reason is that the only ways to reasonably power the furnaces are either with solar power, or with a charcoal production engine. The first limits base construction, and the second ignores the work that gets put in to getting this far.

### Additional things

Pretty please? If/when you have the time to do it. This is a nicety, so should have low priority.

**Comment by DevDyna** [comment]
*Feature* implemented on latest commit [85be367e1028bf222df54084d462710d0495b53a] so it will be implemented on latest release (probably 1.0)

**Comment by DevDyna** [comment]
*Feature* has been extended in more other recipes [[09.11.24 -> 11.11.24 -> ...](https://github.com/DevDyna/IronBerry/commits/main/?since=2024-11-09&until=2024-11-11)]
