### ISSUE TITLE
Uncraftable items.

### ISSUE THREAD

**Issue by ZariusCorten** [DevDyna/IronBerry#35]
### Core Section

- [X] I have searched on opened [issues](https://github.com/DevDyna/IronBerry/issues) and [discussions](https://github.com/DevDyna/IronBerry/discussions) of this repository
- [X] I'm using the latest version of this project

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.9c hotfix 3

### Description

Bed is uncraftable. (Not actually sure if this is intended, but I thought I'd throw it in.)

Block of Ruby is uncraftable. (Assuming this is *not* inteded, as it has a use and it has a recipe that breaks it down in to rubies, but no obvious method of obtainment.)

### Procedure

Attempt to craft them.

### Additional things

That is all.

**Comment by DevDyna** [comment]
thank to report it ! i will investigate on that as soon as possible

**Comment by DevDyna** [comment]
Apparently that was caused due some ingredient filters so.. i will try to fix (it wasn't caused by me but probably some unsupported mods)
