### ISSUE TITLE
Broken Recipes - Centrifuge and Ingot Former

### ISSUE THREAD

**Issue by ZariusCorten** [DevDyna/IronBerry#36]
### Core Section

- [X] I have searched on opened [issues](https://github.com/DevDyna/IronBerry/issues) and [discussions](https://github.com/DevDyna/IronBerry/discussions) of this repository
- [X] I'm using the latest version of this project

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.9c hotfix 3

### Description

The recipes for the Nuclearcraft Ingot Former and Centrifuge don't work properly. The alloy furnace registers the Blulectric Alloy Furnace in it first, and runs that recipe resulting in two iron ingots rather than the intended item. 

### Procedure

Run the recipe.

### Additional things

I am uncertain of there *are* any recipes that utilize the regular Blulectric furnace, but I suggest moving the recipe that converts both the Blulectric Furnace and the Blulectric Alloy Furnace to the vanilla Furnace recipes.

I might actually suggest utilizing the vanilla Furnace for *all* single input items that produce a single output item, where logically appropriate. It's more work, but I suspect it'll fix similar issues we just haven't discovered yet.

**Comment by DevDyna** [comment]
thank to report it !
so... i have tested and apparently it send priority on all bluepower hardcoded recipes so... i can't remove or move on any way
i have try to disable that via configs but apparently the entire config dont want to respond...
so i have found a good solution -> remove by recipe type id and it work as intended (but on jei persist , idk why)
