### ISSUE TITLE
Broken Recipes - mekanism upgrades

### ISSUE THREAD

**Issue by ZariusCorten** [DevDyna/IronBerry#37]
### Core Section

- [X] I have searched on opened [issues](https://github.com/DevDyna/IronBerry/issues) and [discussions](https://github.com/DevDyna/IronBerry/discussions) of this repository
- [X] I'm using the latest version of this project

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.9c hotfix 3

### Description

Energy Upgrade and Speed Upgrade from Mekanism are none-functional. Rather than producing the desired item, it melts down the Pressure Gauge in to four gold ingots.

### Procedure

Manual test of recipe should replicate results.

### Additional things

The usual suggestions: Change recipe priority, change machine of one of the conflicting recipes, or change a needed item.

**Comment by ZariusCorten** [comment]
I suggest checking the Nuclearcraft Neoteric versions, as well, as their recipes use almost the same, exact recipe.

**Comment by DevDyna** [comment]
> Modpack Version
0.9c hotfix 3

i have released 0.9d so try if persist or not

also there is a discussion about missing/broken recipes -> https://github.com/DevDyna/IronBerry/discussions/27
