### ISSUE TITLE
server settings

### ISSUE THREAD

**Issue by trekinsanity** [DevDyna/IronBerry#38]
### Core Section

- [X] I have searched for this issue on this repository

### Stage Selection

None

### MOD Selection

None

### QUEST Selection

None

### RECIPES / EVENTS Selection

None

### Summary

Love the pack. I want to play with friends. What is the level-type?

**Comment by DevDyna** [comment]
> Love the pack. I want to play with friends. What is the level-type?

it should be `skyblockbuilder:skyblock` (except changes of Skyblock Builder)

**Comment by trekinsanity** [comment]
is it skyblockbuilder\:custom_skyblock?
