### ISSUE TITLE
Jei problem?

### ISSUE THREAD

**Issue by Enryco** [DevDyna/IronBerry#7]
Not be able to view the recipe of something from the quest is kinda annoying. Also if i press U on a ceramic bucket of Ironberry Juice or Crude Oil, i expet to see a recipe of the liquid process in the Evaporating Basin, but it show nothing, so i need to search the usage of the liquid in Jei

**Comment by DevDyna** [comment]
> Also if i press U on a ceramic bucket
probably you need to press U on fluid , ceramic buckets use nbt ,
on next release i already hidden all useless buckets from them with nbt
[i can't modify that because can cause thousand of issues like on jei ]
