### ISSUE TITLE
Quest Hidden

### ISSUE THREAD

**Issue by Enryco** [DevDyna/IronBerry#9]
In the first chapter I found the cauldron and crucible quest hidden.
It seems like the chapter is complete, but when i make the cauldron it complete and unlock the quest for it, same when i pick up the crucible.
Completing this hidden quest also unlock the capter 2, which was aso hidden

**Comment by DevDyna** [comment]
i will investigate on that

**Comment by DevDyna** [comment]
i will fix it on next 0.7c with a few of new things but without quests (chapter 4)
